apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: accounts-tls-certs                                                                                                                                                      base64 data at input by
  namespace: accounts                                                                                                                                                           WS0t|...
data:
  tls.crt: |
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    MDYyOTEyMjMyMFowFzEVMBMGA1UEAwwMYWNjb3VudHMuc3ZjMIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvSXj/2Iy0IAm9uZPICvJdYv3AlyEZ1Ab0SsH
    jgVBw/lcbP4q8NC5J/h462fvvKORLafH10ZEnjTxc4wp9ODTqHwbNYR+zBEATDqI
    y2mlgu2A2bdYPpY9EjozDsH/50V6wEbuF4xJWjQZbzHlKJ7dg/PP26OgjtCJUqSC
    SnZt34jn54gr6Meg1r6tSKw5r+5obITc4rqZGrEqAFl2en593ZbfzzJRX7JuwuTA
    OYCWLCHdYoW4Iwjr8BP+EZDd5DTm+Nl0unfoNuGmqm8M4x4s6bE34SEvnueHQy4u
    pc1FW26S7U3zOPJmskal1ruUVEVJbZEDokmwPjtzXjPTg2QiCQIDAQABo1MwUTAd
    BgNVHQ4EFgQUVmaZb6xRiq1mtLhmygVxEMNPyRIwHwYDVR0jBBgwFoAUVmaZb6xR
    iq1mtLhmygVxEMNPyRIwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
    AQEAR0tCdNcFYF5gQWUJmDs/V3Bx4y/gpn2Ityvlg+ZA43DOj54UULloSxzRLu8i
    bYKtseav1q1lNilyjV5e0ndE6tK4ccluETEh5wuAWDUwLodxnHSu7sEQVcna2Ido
    vshJm95p4XKOcYnyPBiiY3g8KGvknwVrpJSJfB+09RmL7Z61PdJUTwP7hRnehdNj
    vrmOv8U1+J+JpCfubU0j7/TCQ/wEORYWzTDGBwCImQ4aSHn8TR9WhLACG8uC/G61
    P64ZE/wl6Osg0dpXTB0KdWrO3//faiy5g9K1E4tH4XVjGi0DxEwMmgDmllEfDl+G
    jkbFE58pqc7dI4oKIFtIG9wkBg==

  tls.key: |
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    jCn04NOofBs1hH7MEQBMOojLaaWC7YDZt1g+lj0SOjMOwf/nRXrARu4XjElaNBlv
    MeUont2D88/bo6CO0IlSpIJKdm3fiOfniCvox6DWvq1IrDmv7mhshNziupkasSoA
    WXZ6fn3dlt/PMlFfsm7C5MA5gJYsId1ihbgjCOvwE/4RkN3kNOb42XS6d+g24aaq
    bwzjHizpsTfhIS+e54dDLi6lzUVbbpLtTfM48mayRqXWu5RURUltkQOiSbA+O3Ne
    M9ODZCIJAgMBAAECggEAeUQurdAmZfiTgp3bwvNvwNYQckogdSAuBWeB+3KxXFSm
    BhbaLvSSkObDl6FWWWnArTWxcPpTCd9FoeAOEjqGWLHgu+oLZQfNWhH5G/jKrWtZ
    vbvHbrDhzKrVizOjvoGUFmwjP6Oob5WRbPHfSrC3sl6BN/7q9EUMlZh1FApjnPjO
    DXeB7EdjijAo7CmhyVxfB/EdidalzSzpJT9Niz3NiQ+N7stC2w560dESRp4IqPht
    YFaVQTjQaIt23kwXBYeMUb+slKc3kGDo6aQBNRFHZl/I/Flms8Ms+aAxF13trESO
    D6/+/+RwgMHHfIv3jj++pqMVOE/Mx6iGd4omgRqGlQKBgQDfHLf95Qsl5pBdPHu1
    R0/A/PkJjO81edTjduHyE1p7rVV2gScWZsfjpeh1IwYG3s4ExglJlYXVmO0yZ/fr
    1srU/AUi2VM+8HaJWshBIEsLBlnpyxtaUyCaxfihll9rqznNJDDSpzDSbTPnM3Co
    O3RvYBrBYjaD87dtEfl7NOR9/wKBgQDZB4MXdFEMJ+nPnCoYgwZc4fYiqD8wypXj
    zwmZSR0FgPjVk8+e7axIOZd84sxHyoof4T5FD+vcXyJEH8d5XO15V/WBUmcpmn7r
    mlsD1RaA3tGup9hG98VJU2yHH1yQndKnEHpildE/VEwea5upvT7n91Wp0BViVlcF
    yqrdsbNv9wKBgCKQh2ydFEoN2yWmnh+qaY+jYU16eQCW3EVVAJIJL4Zjhw7x2UVe
    LO92n3muMFvWHqKcr4mn0XES3QRnGQB/aTLvzDfm5T+l7yc+WjHEt/uAQ2O15Ins
    wOtZajhWXHgIsc63IZ0w655d7qGN1ZEqjNJIWDzHY1yz4CHUnArbWd6vAoGBAJaJ
    YWKZacY2wTUiKwjJiVZP3bx4WyxquMFFUHEkh57TsMXkOvUQApouaGdVoUCCuoAW
    amzY+E7pJgl+yYvi601pt362O5xd739Yl5z25x8IbwToo1nGbu/Hj9XB6SDed8kt
    4tYS+QsmW44WMejwvXuE0cRx8wM8xCveQdp4cfBNAoGASHCgKSt4OzdsqIjNjVmz
    Bi8ehdc7mLhNhgiW7EK5G8WdbWN1/QIAmOubOEIm+7xbc6Yk6R+LujdQ/4cy9ofz
    DHcr40fiTRajBlyMPm/ZK46iNFyq3DhGK49SfDGOKvuCode9jhZM/Gf4bJmO9Xgo
    NCycfWFi6g6vlz0dZJOa7c4=
